In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9431, 7507, 3783, 4556],
 [9431, 7507, 3783, 5797],
 [9431, 1181, 3783, 1481],
 [7277, 3278, 8087, 1526, 3486],
 [7277, 3278, 8087, 1526, 6514],
 [132, 9431, 7157, 3783, 5109],
 [6335, 1099, 490, 1526]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9431 7507 3783 4556]
 [   0    0    0    0 9431 7507 3783 5797]
 [   0    0    0    0 9431 1181 3783 1481]
 [   0    0    0 7277 3278 8087 1526 3486]
 [   0    0    0 7277 3278 8087 1526 6514]
 [   0    0    0  132 9431 7157 3783 5109]
 [   0    0    0    0 6335 1099  490 1526]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 226ms/step


array([[[ 4.73504700e-02,  3.51301916e-02,  2.75426544e-02,
         -1.54976919e-03, -4.54759486e-02,  3.61815356e-02,
         -4.62285392e-02, -2.93349866e-02, -4.26322930e-02,
         -4.92126010e-02],
        [ 4.73504700e-02,  3.51301916e-02,  2.75426544e-02,
         -1.54976919e-03, -4.54759486e-02,  3.61815356e-02,
         -4.62285392e-02, -2.93349866e-02, -4.26322930e-02,
         -4.92126010e-02],
        [ 4.73504700e-02,  3.51301916e-02,  2.75426544e-02,
         -1.54976919e-03, -4.54759486e-02,  3.61815356e-02,
         -4.62285392e-02, -2.93349866e-02, -4.26322930e-02,
         -4.92126010e-02],
        [ 4.73504700e-02,  3.51301916e-02,  2.75426544e-02,
         -1.54976919e-03, -4.54759486e-02,  3.61815356e-02,
         -4.62285392e-02, -2.93349866e-02, -4.26322930e-02,
         -4.92126010e-02],
        [-4.12384495e-02, -1.19672306e-02,  4.44423221e-02,
          6.43242523e-03,  2.67666318e-02,  4.93492819e-02,
          3.44213508e-02, -4.61993590e-02,  3.066697

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9431, 7507, 3783, 4556])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 108ms/step


array([[ 0.04735047,  0.03513019,  0.02754265, -0.00154977, -0.04547595,
         0.03618154, -0.04622854, -0.02933499, -0.04263229, -0.0492126 ],
       [ 0.04735047,  0.03513019,  0.02754265, -0.00154977, -0.04547595,
         0.03618154, -0.04622854, -0.02933499, -0.04263229, -0.0492126 ],
       [ 0.04735047,  0.03513019,  0.02754265, -0.00154977, -0.04547595,
         0.03618154, -0.04622854, -0.02933499, -0.04263229, -0.0492126 ],
       [ 0.04735047,  0.03513019,  0.02754265, -0.00154977, -0.04547595,
         0.03618154, -0.04622854, -0.02933499, -0.04263229, -0.0492126 ],
       [-0.04123845, -0.01196723,  0.04444232,  0.00643243,  0.02676663,
         0.04934928,  0.03442135, -0.04619936,  0.03066697,  0.01446662],
       [-0.04034444, -0.03178632,  0.04138707,  0.04198772,  0.01875987,
        -0.02945645,  0.04090427, -0.04374702,  0.01454207,  0.01269453],
       [-0.01437969,  0.00222104, -0.00787317,  0.037556  ,  0.02729077,
         0.0072636 ,  0.02357193, -0.03970505